#!/bin/sh
#
# Creates a single install directory from all the csw stage directories.

dir=../install
stage=target/universal/stage

for i in bin lib conf doc ; do
    test -d $dir/$i || mkdir -p $dir/$i
done

# Ignore the error messages generated by unidoc
sbt -Dcsw.genjavadoc.enabled=true unidoc > .unidoc.log 2>&1
sbt publish-local stage

for i in bin lib ; do
    for j in */target/universal/stage/$i/* apps/*/target/universal/stage/$i/* examples/*/target/universal/stage/$i/* ; do
        cp -f $j $dir/$i
    done
done

rm -rf $dir/doc/*
cp -r target/javaunidoc/ $dir/doc/java
cp -r target/scala-2.11/unidoc/ $dir/doc/scala

rm -f $dir/bin/*.log.* $dir/bin/*.bat

# create the scalas script, for scala scriping (see http://www.scala-sbt.org/release/docs/Scripts.html)
# Note: This depends on the sbt version declared in project/build.properties (0.13.8).
echo 'sbt -Dsbt.main.class=sbt.ScriptMain "$@"' > $dir/bin/scalas
chmod ugo+x $dir/bin/scalas
